### ISSUE TITLE
Project Outline / Summary

### ISSUE THREAD

**Issue by ptheywood** [RSE-Sheffield/exatepp-abm#1]
todo - populate this with the project summary / plan post meeting

---

## Implementation plan

- [x] Create repo
- [x] Empty FLAME GPU model
- [x] Test suite outline, capable of integration and unit testing (subject to time constraints)
- [x] Initial planning
- [x] Initial pure RNG model to get structure in place
  - Basic parameter setting/reading
  - RNG seeding
  - Generate initial agents, who belong to a demographic, basic SIR state.
  - Pure RNG interactions
  - Simulate for parameterised number of days
  - Basic output of time-series data (infection count)
- [ ] Finer-grained interactions
  - Add a submodel, so individual interactions occur in-order?
  - Possibly not required, but would be for some infectivity modes (i.e. indirect infection from the place not the person)
- [ ] Add randomly initialised fixed networks
  - Randomly initialise fixed household network
  - Randomly initialise fixed work/school network
  - Interactions within household network
  - Interactions within work/school network
- [x] Simulation performance outputs
  - Output total and broken down simulation execution time info to file / stdout
- [ ] Add randomly initialised recreation per-day interaction network
  - Changes per day (if feature enabled)
    - May need some flame gpu workarounds
  - Purely random initialisation
  - Add interactions between others in the same random network
- [ ] Realistic network generation
  - Watts-Strogatz small-world networks
  - Need to investigate parallelisation at a later date. Not currently possible within FLAME GPUs API. May need custom CUDA.
- [ ] Enhanced infection modelling
  - More than just S(E)IR, see the reference model
- [ ] Interaction outputs
  - Agents store a history of interactions
  - Optionally Output interaction event data
  - This may have significant performance implications, care will need to be taken
- [ ] Scaling benchmark
  - Run simulation(s) at different population scales, capturing performance information with different features enabled/disabled.
    - I.e. demonstrate that it's not worth it for tiny populations, but suitable and performant for Wales-scale simulations and above.
- [ ] Expand time serious output with additional data

Optional / lower priority features

- [ ] Per individual output file
- [ ] Ensemble support
  - Stochastic model, so ensembles required. Expressing them in FLAME GPU itself could lead to improved performance (for some model scales).
